# Meaning codes keywords
meaning_keywords_dict = {
    "wh_basic": ["who", "what", "when", "where", "which"],
    "why": ["why"],
    "how": ["how"],
    "sequence_temporal": [
        "first",
        "second",
        "third",
        "next",
        "last",
        "begin",
        "beginning",
        "middle",
        "end",
        "after",
        "earlier",
        "before",
        "final",
        "finally",
        "day",
        "yesterday",
        "today",
        "tomorrow",
        "time",
        "meantime",
        "sometime",
        "minute",
        "second",
        "morning",
        "daytime",
        "evening",
        "nighttime",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ],
    "compare_contrast": [
        "like",
        "likewise",
        "similar",
        "same",
        "different",
        "difference",
        "opposites",
        "contrast",
        "compare",
        "comparison",
        "alike",
        "not alike",
    ],
    "cognition": [
        "learn",
        "think",
        "know",
        "believe",
        "make believe",
        "plan",
        "pretend",
        "doubt",
        "marvel",
        "remember",
        "recall",
        "forget",
        "guess",
        "dream",
        "visualize",
        "imagine",
        "understand",
        "figure it out",
        "have in mind",
        "change mind",
        "realize",
        "consider",
        "come up with",
        "decide",
        "decision",
        "pick",
        "choice",
        "choose",
    ],
    "desires_preferences": [
        "dislike",
        "don’t like",
        "love",
        "fond",
        "keen",
        "enjoy",
        "want",
        "prefer",
        "favorite",
        "hate",
        "can’t stand",
        "hope",
        "wish",
    ],
    "feelings_emotions": [
        "feel",
        "feeling",
        "feelings",
        "emotion",
        "emotions",
        "happy",
        "joyful",
        "serene",
        "calm",
        "relaxed",
        "ecstatic",
        "glad",
        "gleeful",
        "proud",
        "confident",
        "sad",
        "grumpy",
        "pensive",
        "serious",
        "solemn",
        "grieving",
        "depressed",
        "lonely",
        "discouraged",
        "disappointed",
        "fear",
        "worried",
        "apprehensive",
        "scared",
        "afraid",
        "frightened",
        "terrified",
        "anxious",
        "concerned",
        "shy",
        "self-conscious",
        "embarrassed",
        "angry",
        "annoyed",
        "stressed",
        "overwhelmed",
        "frustrated",
        "upset",
        "irritated",
        "mad",
        "furious",
        "crabby",
        "contempt",
        "hatred",
        "aggressive",
        "jealous",
        "anticipation",
        "interested",
        "vigilant",
        "optimistic",
        "surprised",
        "excited",
        "startled",
        "dazed",
        "confused",
        "awe",
        "disgusted",
        "bored",
        "apathetic",
        "loathing",
        "remorseful",
        "sorry",
        "trusting",
        "admiration",
        "accepted",
        "secure",
        "loved",
        "thankful",
        "forgiven",
        "miss",
    ],
    "judgments_perspectives": [
        "mean",
        "nice",
        "boss",
        "bossy",
        "bossing",
        "compliant",
        "fair",
        "unfair",
        "fun",
        "boring",
        "beautiful",
        "ugly",
        "brave",
        "timid",
        "scaredy cat",
        "egotistic",
        "impulsive",
        "obedient",
        "risky",
        "agreeable",
        "cool",
        "amazing",
        "awesome",
        "friendly",
        "fancy",
        "intelligent",
        "smart",
        "stupid",
        "creative",
        "faithful",
        "dishonest",
        "honest",
        "loving",
        "nurturing",
        "important",
        "inferior",
        "respectful",
        "powerful",
        "successful",
        "bully",
        "Acceptable",
        "inadequate",
        "good",
        "bad",
        "okay",
        "best",
        "worst",
        "perfect",
        "wonderful",
        "horrible",
        "terrible",
        "disaster",
        "should",
        "supposed to",
        "must",
        "Agree",
        "disagree",
        "doesn’t make sense",
        "argue",
        "reject",
        "accept",
        "contend",
        "claim",
        "submit",
    ],
    "causaleffects_problemsolve": [
        "because",
        "‘cause",
        "cuz",
        "why",
        "since",
        "cause",
        "effect",
        "reason",
        "if-then",
        "if",
        "then",
        "solve",
        "solution",
        "problem",
        "challenge",
        "trouble",
        "dilemma",
        "conundrum",
        "work out",
        "resolve",
        "attempt",
        "fix",
        "mend",
        "repair",
    ],
    "predictions_forecast": [
        "expect",
        "anticipate",
        "will happen next",
        "could happen next",
    ],
}
